
name: Docker Image Core CI/CD

on:
  push:
    branches: [main]  # 在main分支有push操作的时候自动部署


jobs:
  api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dotnet 7.0.102
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 7.0.x
          include-prerelease: True
      - name: Build
        run: dotnet build Acme.BookStore.sln

      - name: Publish 
        run: dotnet publish src/Acme.BookStore.Web/Acme.BookStore.Web.csproj -o src/Acme.BookStore.Web/publish

      - name: Setting Version
        id: vars
        run: echo ::set-output name=RELEASE_VERSION::$(echo ${GITHUB_REF:10})

      # docker login
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 设置 docker 环境
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # build 并且 push docker 镜像
      - name: Push Acme.BookStore.Web Image
        uses: docker/build-push-action@v2
        with:
          context: src/Acme.BookStore.Web
          push: true
          tags: zhongbodong/lion.abp.pro:${{ steps.vars.outputs.RELEASE_VERSION }}



